timeout:
  startup: 60s
  shutdown: 60s
logger:
  format: text
  stackTrace: false
server:
  http:
    host: '0.0.0.0'
    port: 28420
postgres:
  host: localhost
  port: 5432
  database: meetup
  user: user
  password: user123
  log:
    level: warn
    slowQuery: 200ms
