definitions:
  http.createUserReq:
    properties:
      nickname:
        example: redshore
        type: string
    type: object
  http.createUserResp:
    properties:
      createdAt:
        example: "2022-08-20T18:54:53.965295+09:00"
        type: string
      id:
        example: 412
        type: integer
      nickname:
        example: redshore
        type: string
      updatedAt:
        example: "2022-08-20T18:54:53.965295+09:00"
        type: string
    type: object
  http.deleteUserResp:
    properties:
      id:
        example: 412
        type: integer
    type: object
  http.errorResp:
    properties:
      msg:
        type: string
    type: object
  http.getUserResp:
    properties:
      createdAt:
        example: "2022-08-20T18:54:53.965295+09:00"
        type: string
      id:
        example: 412
        type: integer
      nickname:
        example: redshore
        type: string
      updatedAt:
        example: "2022-08-20T18:54:53.965295+09:00"
        type: string
    type: object
info:
  contact: {}
  description: API gateway for Meetup project.
  title: Meetup Gateway
  version: "1.0"
paths:
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: Create an user.
      parameters:
      - description: Request to create an user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.createUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.createUserResp'
        default:
          description: Somethings got wrong
          schema:
            $ref: '#/definitions/http.errorResp'
      tags:
      - Users
  /api/v1/users/{userId}:
    delete:
      description: Delete an user.
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.deleteUserResp'
        default:
          description: Somethings got wrong
          schema:
            $ref: '#/definitions/http.errorResp'
      tags:
      - Users
    get:
      description: Get an user.
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.getUserResp'
        default:
          description: Somethings got wrong
          schema:
            $ref: '#/definitions/http.errorResp'
      tags:
      - Users
swagger: "2.0"
